#!/bin/sh

# Print battery percentage in the following format: "34%"
# If not charging, also print remaining battery time.
acpi -i | grep -B 1 design | head -n1 | awk '{
                split($0, a, ", ");
                printf "%s", a[2];
                split(a[1], b, ": "); 
                if(b[2] == "Discharging") {
                    time = substr(a[3],1,5);
                    printf " %s", time;
                }
                print ""
            }'

