#!/bin/sh

# Handle SIGTRAP signals sent by refresh script to update the status bar.
trap 'update' 5

status() { \
    if  ip route get 1.2.3.4 > /dev/null; then 
        ip route get 1.2.3.4 | grep "src" | awk 'NR==1{ print $5 " " $7 }'
    else
        printf "offline "
    fi    
 
    printf "| "
    if [ "$(pulsemixer --get-mute)" = "1" ]; then 
        printf "mut"
    else
        vol=$(pulsemixer --get-volume | awk '{print $1}')
        printf "vol: %s %s%%\\n" "$icon" "$vol"
    fi

    printf " | "
    printf "⚡"; printf "%s" "$(battery)"

    printf " | "
    setxkbmap -query | grep layout | awk  '{print $2}'

    printf "| "
    date +"%H:%M %A %d.%m.%Y"
}

update() { \
    xsetroot -name "$(status | tr '\n' ' ')" &
    wait
}

while :; do
    update
    sleep 10 &
    wait
done

